// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsEventsManagement.Data;

#nullable disable

namespace SportsEventsManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260105205957_AddTourColumn")]
    partial class AddTourColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsEventsManagement.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TournoiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournoiId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("SportsEventsManagement.Models.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("SportsEventsManagement.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateMatch")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EquipeDomicileId")
                        .HasColumnType("int");

                    b.Property<int?>("EquipeExterieurId")
                        .HasColumnType("int");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScoreDomicile")
                        .HasColumnType("int");

                    b.Property<int>("ScoreExterieur")
                        .HasColumnType("int");

                    b.Property<int>("Tour")
                        .HasColumnType("int");

                    b.Property<int>("TournoiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeDomicileId");

                    b.HasIndex("EquipeExterieurId");

                    b.HasIndex("TournoiId");

                    b.ToTable("Matchs");
                });

            modelBuilder.Entity("SportsEventsManagement.Models.Tournoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombreEquipesMax")
                        .HasColumnType("int");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tournois");
                });

            modelBuilder.Entity("SportsEventsManagement.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("SportsEventsManagement.Models.Equipe", b =>
                {
                    b.HasOne("SportsEventsManagement.Models.Tournoi", "Tournoi")
                        .WithMany("Equipes")
                        .HasForeignKey("TournoiId");

                    b.Navigation("Tournoi");
                });

            modelBuilder.Entity("SportsEventsManagement.Models.Joueur", b =>
                {
                    b.HasOne("SportsEventsManagement.Models.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("SportsEventsManagement.Models.Match", b =>
                {
                    b.HasOne("SportsEventsManagement.Models.Equipe", "EquipeDomicile")
                        .WithMany()
                        .HasForeignKey("EquipeDomicileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportsEventsManagement.Models.Equipe", "EquipeExterieur")
                        .WithMany()
                        .HasForeignKey("EquipeExterieurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SportsEventsManagement.Models.Tournoi", "Tournoi")
                        .WithMany("Matchs")
                        .HasForeignKey("TournoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipeDomicile");

                    b.Navigation("EquipeExterieur");

                    b.Navigation("Tournoi");
                });

            modelBuilder.Entity("SportsEventsManagement.Models.Tournoi", b =>
                {
                    b.Navigation("Equipes");

                    b.Navigation("Matchs");
                });
#pragma warning restore 612, 618
        }
    }
}
